### ISSUE TITLE
JS-main page 

### ISSUE THREAD

**Issue by gwengibbes** [gwengibbes/com6338-module10-assignment10-gibbes-longo-avery#20]
Call the API to get the list of food pairings based on the selected wine

**Comment by ElodieLongo** [comment]
Thank you Gwen, here we should check together because I am not sure how you want to do this as I had a slightly different thing in mind. See my other comments on this topic.

**Comment by gwengibbes** [comment]
Can you make the time suggested tomorrow to meet? Let’s discuss then.
I think changing things at this last minute is going to make things harder.
Either way we must meet asap.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ElodieLongo** [comment]
Closing since this is a duplicate of issue #1
