### ISSUE TITLE
JS-Gater APIs URLs and keys

### ISSUE THREAD

**Issue by ElodieLongo** [gwengibbes/com6338-module10-assignment10-gibbes-longo-avery#3]

**Comment by ElodieLongo** [comment]
`/* Spoonacular API */

const SpoonacularKey = "*****************************";

let FindRecipeUrl = "https://api.spoonacular.com/recipes/findByIngredients?ingredients=meat&number=3";


/* Edamam API */
 Access Point: https://api.edamam.com/api/recipes/v2


Application ID:

22b25df1

This is the application ID, you should send with each API request.
Application Keys
fedc606a902ac509ffa30b75cad44f35 	— 
`

**Comment by ElodieLongo** [comment]
Hi Gwen, I have added the API URLs and Keys to the comments while I try to figure out why it is not letting me push request.  So this issue can be closed as soon as I manage to push the info. I'll try re-cloning the repository.

**Comment by gwengibbes** [comment]
Okay sounds good.
If you get stuck, maybe send us some screenshots of what is happening on your end?
________________________________
