### ISSUE TITLE
Move code from  "index.js" to "wine-family-selection.js"

### ISSUE THREAD

**Issue by ElodieLongo** [gwengibbes/com6338-module10-assignment10-gibbes-longo-avery#30]

**Comment by ghost** [comment]
@ElodieLongo @gwengibbes Wanted to note that the homepage is currently linked to two JS sheets. I didn't wanna touch anything but wanted to bring it up if that was still being worked on.

**Comment by ElodieLongo** [comment]
@jordanatuf @gwengibbes 

I tried to do what described by this issue but it was creating some bugs so I will close it and let it separate. I removed the edamame key that was not needed as discussed in our meeting.
